version: "3.9"
services:
  memcached:
    platform: linux/arm64
    image: arm64v8/memcached
    ports:
      - 11211:11211

  redis:
    platform: linux/amd64
    image: redis:7.0.4-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: